version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/node:14.16.0
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: cimg/node:14.16.0
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          command: npm test
          name: Run tests
  check_queue:
    docker:
      - image: cimg/node:14.16.0
    steps:
      - checkout
      - run: npm install
      - run:
          command: node scripts/check_queue.js
          environment:
            DEFAULT_BRANCH: master
            QUEUE_CHECK_FREQUENCY: 30
          name: Run queue script
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - check_queue:
          filters:
            branches:
              only:
                - master
      - build:
          requires:
            - check_queue
      - test:
          requires:
            - check_queue
            - build